#
# add_newline = false
#
#
[line_break]
disabled = true

# enable_transience = true
#
# # Replace the "❯" symbol in the prompt with "➜"
# [character] # The name of the module we are configuring is "character"
# success_symbol = "[➜](bold green)" # The "success_symbol" segment is being set to "➜" with the color "bold green"


right_format = """$battery$time"""
# Prompt: param 2 └─

[character]
success_symbol = " [ ](#B588F3)"
error_symbol = " [ ](#d47d85)"
# error_symbol = " [ ](#d47d85)"
vicmd_symbol = "[  ](#A3BE8C)"

# Username
[username]
style_user = "dimmed blue"

[hostname]
ssh_only = false
format = "<[$hostname]($style)>"
trim_at = "-"
style = "dimmed white"
disabled = true

[battery]
full_symbol = ""
charging_symbol = ""
discharging_symbol = ""
unknown_symbol = ""
disabled = false
format = "[ ](fg:#423840 bg:none)[$symbol ](fg:#d47d85 bg:#423840)[ ](fg:#423840 bg:#282c34)[$percentage]($style)[ ](fg:#282c34 bg:none)"
[[battery.display]]
style = "fg:#d47d85 bg:#282c34"
threshold=100

# Last param in the first line/row
[cmd_duration]
min_time = 1
format = "[ ](fg:#40394F bg:none)[ ](fg:#c882e7 bg:#40394F)[](fg:#40394F bg:#282c34)[$duration]($style)[](fg:#282c34 bg:none)"
disabled = false
style = "fg:#c882e7 bg:#282c34"

# Third param
[directory]
format = "[](fg:#413D3B bg:none)[ ](fg:#d19a66 bg:#413D3B)[](fg:#413D3B bg:#282c34)[ $path]($style)[](fg:#282c34 bg:none) "
style = "fg:#d19a66 bg:#282c34"
truncation_length = 3
truncate_to_repo=false

[git_branch]
format = "[](fg:#3A4241 bg:none)[ ](fg:#A3BE8C bg:#3A4241)[](fg:#3A4241 bg:#282c34)[ $branch]($style)[](fg:#282c34 bg:none) "
style = "fg:#A3BE8C bg:#282c34"

[git_commit]
format = "[\\($hash\\)]($style) [\\($tag\\)]($style)"
style = "green"

[git_status]
format="[](fg:#314050 bg:none)[ ](fg:#61afef bg:#314050)[ ](fg:#314050 bg:#282c34)[$modified](fg:#61afef bg:#282c34)[$untracked](fg:#61afef bg:#282c34)[$staged](fg:#61afef bg:#282c34)[$renamed](fg:#61afef bg:#282c34)[$ahead_behind](fg:#61afef bg:#282c34)[](fg:#282c34 bg:none)"
conflicted = "="
ahead =	"⇡${count} "
behind = "⇣${count} "
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
untracked = "?${count} "
modified = "!${count} "
staged = "+${count} "
renamed = "»${count} "
deleted = "✘${count} "
style =	"red"
disabled = false

[git_state]
rebase = "REBASING"
merge =	"MERGING"
revert = "REVERTING"
cherry_pick = "CHERRY-PICKING"
bisect = "BISECTING"
am = "AM"
am_or_rebase = "AM/REBASE"
style =	"yellow"
format = '\([$state( $progress_current/$progress_total)]($style)\) '
disabled = false

[hg_branch]
symbol = ""
style = "purple"
format = "on [$symbol$branch]($style) "

[time]
style="fg:#61afef bg:#282c34"
format="[](fg:#314050 bg:none)[ ](fg:#61afef bg:#314050)[](fg:#314050 bg:#282c34)[ $time]($style)[](fg:#282c34 bg:none)"
time_format = "%R"
disabled = false

[docker_context]
disabled=true
symbol = " "

[c]
disabled=true

[conda]
disabled=true
symbol = " "

[dart]
disabled=true
symbol = " "

[package]
disabled=true
symbol = " "

[perl]
disabled=true
symbol = " "

[php]
disabled=true
symbol = " "

# [go]
# disabled= false
# symbol = "ʕ◔ϖ◔ʔ"
# format = 'via [${symbol}${goenv_prefix}${version}( $virtualenv)]($style) '
# style = "italic Blue"

[ruby]
disabled=true
symbol = " "

[java]
disabled=true
symbol = " "

[lua]
disabled=true
symbol = " "
style = "bold blue"

[nodejs]
disabled=true

[swift]
disabled=true
symbol = "ﯣ "

[julia]
disabled=true
format = "[$symbol$version]($style) "
symbol = "ஃ "
style = "bold green"

[python]
disabled=false
format = 'via [${symbol}${pyenv_prefix}${version}( $virtualenv)]($style) '
symbol = " "
style = "italic Blue"

[rust]
disabled=true
format = "[$symbol$version]($style) "
# style = "bold green"
symbol = " "

[zig]
disabled=true
# Prompt: optional param 1
